-- Migration: Create manufacturers reference table
-- Based on MC4EB Publication 7, Change 1 - Equipment Manufacturer Codes
-- Used in SFAF fields: 340 (Transmitter Equipment), 354 (Transmitter Antenna),
--                       440 (Receiver Equipment), 453 (Receiver Antenna)

CREATE TABLE IF NOT EXISTS manufacturers (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code        VARCHAR(10) UNIQUE NOT NULL,
    name        VARCHAR(255) NOT NULL,
    country     VARCHAR(100),
    is_active   BOOLEAN DEFAULT true,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_manufacturers_code ON manufacturers(code);
CREATE INDEX IF NOT EXISTS idx_manufacturers_name ON manufacturers(name);

-- Seed data: MC4EB Publication 7, Change 1 - Equipment Manufacturer Codes
INSERT INTO manufacturers (code, name, country) VALUES
    ('ADC', 'ADC Telecommunications', 'USA'),
    ('AEG', 'AEG Aktiengesellschaft', 'Germany'),
    ('AIT', 'Advanced Information Technology', 'USA'),
    ('AMP', 'Amphenol Corporation', 'USA'),
    ('AOR', 'AOR Ltd', 'Japan'),
    ('ARI', 'Aeronautical Radio Inc', 'USA'),
    ('BAR', 'Barrett Communications', 'Australia'),
    ('BRG', 'Bren-Tronics Inc', 'USA'),
    ('CAL', 'California Amplifier Inc', 'USA'),
    ('CMC', 'CMC Electronics Inc', 'Canada'),
    ('COL', 'Collins Aerospace (Rockwell Collins)', 'USA'),
    ('COM', 'COM DEV International', 'Canada'),
    ('CTC', 'CTC Communications Corp', 'USA'),
    ('DAI', 'DAI Technologies', 'USA'),
    ('DRS', 'DRS Defense Solutions LLC', 'USA'),
    ('EFJ', 'EF Johnson Technologies', 'USA'),
    ('EMS', 'EMS Technologies Inc', 'Canada'),
    ('ERI', 'Ericsson Inc', 'Sweden'),
    ('GAL', 'Galil Motion Control', 'USA'),
    ('GDC', 'General Dynamics Communications', 'USA'),
    ('GEC', 'GEC-Marconi Communications', 'UK'),
    ('HAR', 'Harris Corporation (L3Harris)', 'USA'),
    ('HER', 'Herley Industries Inc', 'USA'),
    ('HIT', 'Hitachi America Ltd', 'Japan'),
    ('HUG', 'Hughes Network Systems', 'USA'),
    ('IBM', 'International Business Machines', 'USA'),
    ('IFR', 'IFR Systems Inc', 'USA'),
    ('ITT', 'ITT Defense Electronics & Services', 'USA'),
    ('JRC', 'Japan Radio Co Ltd', 'Japan'),
    ('KEN', 'Kenwood Corporation', 'Japan'),
    ('KYM', 'Kymeta Corporation', 'USA'),
    ('L3C', 'L3 Technologies (L3Harris)', 'USA'),
    ('LNR', 'LNR Communications Inc', 'USA'),
    ('MAC', 'MacCom Inc', 'USA'),
    ('MAR', 'Marconi Communications', 'UK'),
    ('MIL', 'Milcom Systems Inc', 'USA'),
    ('MIT', 'MITRE Corporation', 'USA'),
    ('MOT', 'Motorola Solutions Inc', 'USA'),
    ('MSC', 'Mobile Satellite Communications', 'USA'),
    ('NEC', 'NEC Corporation', 'Japan'),
    ('NOK', 'Nokia Corporation', 'Finland'),
    ('NOR', 'Northrop Grumman Corporation', 'USA'),
    ('OCC', 'Optical Communications Corp', 'USA'),
    ('PAC', 'Pacific Defense Solutions', 'USA'),
    ('PRC', 'Proxim Wireless Corporation', 'USA'),
    ('QUA', 'Qualcomm Government Technologies', 'USA'),
    ('RAY', 'Raytheon Intelligence & Space', 'USA'),
    ('RCA', 'RCA Corporation (legacy)', 'USA'),
    ('SAM', 'Samsung Electronics', 'South Korea'),
    ('SCI', 'SCI Systems Inc', 'USA'),
    ('SIE', 'Siemens AG', 'Germany'),
    ('STA', 'Standard Communications Corp', 'USA'),
    ('STN', 'Stanford Telecom', 'USA'),
    ('TEN', 'Tenix Defence', 'Australia'),
    ('THA', 'Thales Group', 'France'),
    ('TRC', 'Transcrypt International', 'USA'),
    ('UNI', 'Uniden Corporation', 'Japan'),
    ('VER', 'Vertex Standard Co Ltd', 'Japan'),
    ('VIA', 'Viasat Inc', 'USA'),
    ('WAT', 'Watkins-Johnson Company', 'USA'),
    ('WHE', 'Wheeler Industries Inc', 'USA'),
    ('WNC', 'WNC Global Inc', 'Taiwan')
ON CONFLICT (code) DO NOTHING;
