-- Migration 024: Seed common US military installations
INSERT INTO installations (name, code, organization, state, country) VALUES
-- Air Force
('Hurlburt Field',              'HURLBURT',     'Air Force',    'FL', 'USA'),
('Eglin Air Force Base',        'EGLIN',         'Air Force',    'FL', 'USA'),
('Tyndall Air Force Base',      'TYNDALL',       'Air Force',    'FL', 'USA'),
('MacDill Air Force Base',      'MACDILL',       'Air Force',    'FL', 'USA'),
('Patrick Space Force Base',    'PATRICK',       'Space Force',  'FL', 'USA'),
('Langley Air Force Base',      'LANGLEY',       'Air Force',    'VA', 'USA'),
('Joint Base Langley-Eustis',   'JBLE',          'Joint',        'VA', 'USA'),
('Joint Base Andrews',          'ANDREWS',       'Joint',        'MD', 'USA'),
('Joint Base Anacostia-Bolling','JBAB',          'Joint',        'DC', 'USA'),
('Nellis Air Force Base',       'NELLIS',        'Air Force',    'NV', 'USA'),
('Creech Air Force Base',       'CREECH',        'Air Force',    'NV', 'USA'),
('Kirtland Air Force Base',     'KIRTLAND',      'Air Force',    'NM', 'USA'),
('Holloman Air Force Base',     'HOLLOMAN',      'Air Force',    'NM', 'USA'),
('Cannon Air Force Base',       'CANNON',        'Air Force',    'NM', 'USA'),
('Edwards Air Force Base',      'EDWARDS',       'Air Force',    'CA', 'USA'),
('Travis Air Force Base',       'TRAVIS',        'Air Force',    'CA', 'USA'),
('Vandenberg Space Force Base', 'VANDENBERG',    'Space Force',  'CA', 'USA'),
('March Air Reserve Base',      'MARCH',         'Air Force',    'CA', 'USA'),
('Luke Air Force Base',         'LUKE',          'Air Force',    'AZ', 'USA'),
('Davis-Monthan Air Force Base','DAVISMONTHAN',  'Air Force',    'AZ', 'USA'),
('Buckley Space Force Base',    'BUCKLEY',       'Space Force',  'CO', 'USA'),
('Peterson Space Force Base',   'PETERSON',      'Space Force',  'CO', 'USA'),
('Schriever Space Force Base',  'SCHRIEVER',     'Space Force',  'CO', 'USA'),
('Barksdale Air Force Base',    'BARKSDALE',     'Air Force',    'LA', 'USA'),
('Keesler Air Force Base',      'KEESLER',       'Air Force',    'MS', 'USA'),
('Columbus Air Force Base',     'COLUMBUS',      'Air Force',    'MS', 'USA'),
('Maxwell Air Force Base',      'MAXWELL',       'Air Force',    'AL', 'USA'),
('Robins Air Force Base',       'ROBINS',        'Air Force',    'GA', 'USA'),
('Moody Air Force Base',        'MOODY',         'Air Force',    'GA', 'USA'),
('Shaw Air Force Base',         'SHAW',          'Air Force',    'SC', 'USA'),
('Seymour Johnson Air Force Base','SEYMOURJOHNSON','Air Force',  'NC', 'USA'),
('Pope Army Airfield',          'POPE',          'Army',         'NC', 'USA'),
('Joint Base Charleston',       'JB CHARLESTON', 'Joint',        'SC', 'USA'),
('Joint Base McGuire-Dix-Lakehurst','JBMDL',    'Joint',        'NJ', 'USA'),
('Hanscom Air Force Base',      'HANSCOM',       'Air Force',    'MA', 'USA'),
('Westover Air Reserve Base',   'WESTOVER',      'Air Force',    'MA', 'USA'),
('Dyess Air Force Base',        'DYESS',         'Air Force',    'TX', 'USA'),
('Goodfellow Air Force Base',   'GOODFELLOW',    'Air Force',    'TX', 'USA'),
('Joint Base San Antonio',      'JBSA',          'Joint',        'TX', 'USA'),
('Laughlin Air Force Base',     'LAUGHLIN',      'Air Force',    'TX', 'USA'),
('Sheppard Air Force Base',     'SHEPPARD',      'Air Force',    'TX', 'USA'),
('Whiteman Air Force Base',     'WHITEMAN',      'Air Force',    'MO', 'USA'),
('Scott Air Force Base',        'SCOTT',         'Air Force',    'IL', 'USA'),
('Grand Forks Air Force Base',  'GRANDFORKS',    'Air Force',    'ND', 'USA'),
('Minot Air Force Base',        'MINOT',         'Air Force',    'ND', 'USA'),
('Ellsworth Air Force Base',    'ELLSWORTH',     'Air Force',    'SD', 'USA'),
('F.E. Warren Air Force Base',  'WARREN',        'Air Force',    'WY', 'USA'),
('Malmstrom Air Force Base',    'MALMSTROM',     'Air Force',    'MT', 'USA'),
('Mountain Home Air Force Base','MOUNTAINHOME',  'Air Force',    'ID', 'USA'),
('Fairchild Air Force Base',    'FAIRCHILD',     'Air Force',    'WA', 'USA'),
('McChord Field (JBLM)',        'JBLM',          'Joint',        'WA', 'USA'),
('Elmendorf-Richardson (JBER)', 'JBER',          'Joint',        'AK', 'USA'),
('Eielson Air Force Base',      'EIELSON',       'Air Force',    'AK', 'USA'),
('Joint Base Pearl Harbor-Hickam','JBPHH',       'Joint',        'HI', 'USA'),
('Kadena Air Base',             'KADENA',        'Air Force',    'Okinawa', 'Japan'),
('Misawa Air Base',             'MISAWA',        'Air Force',    'Aomori', 'Japan'),
('Yokota Air Base',             'YOKOTA',        'Air Force',    'Tokyo', 'Japan'),
('Osan Air Base',               'OSAN',          'Air Force',    'Gyeonggi', 'South Korea'),
('Kunsan Air Base',             'KUNSAN',        'Air Force',    'North Jeolla', 'South Korea'),
('Ramstein Air Base',           'RAMSTEIN',      'Air Force',    'Rhineland-Palatinate', 'Germany'),
('Spangdahlem Air Base',        'SPANGDAHLEM',   'Air Force',    'Rhineland-Palatinate', 'Germany'),
('Aviano Air Base',             'AVIANO',        'Air Force',    'Friuli-Venezia Giulia', 'Italy'),
('RAF Lakenheath',              'LAKENHEATH',    'Air Force',    'Suffolk', 'UK'),
('RAF Mildenhall',              'MILDENHALL',    'Air Force',    'Suffolk', 'UK'),
('RAF Alconbury',               'ALCONBURY',     'Air Force',    'Cambridgeshire', 'UK'),
('Al Udeid Air Base',           'ALUDEID',       'Air Force',    'Ar-Rayyan', 'Qatar'),
('Al Dhafra Air Base',          'ALDHAFRA',      'Air Force',    'Abu Dhabi', 'UAE'),
-- Army
('Fort Liberty (Bragg)',        'FTLIBERTY',     'Army',         'NC', 'USA'),
('Fort Campbell',               'FTCAMPBELL',    'Army',         'KY', 'USA'),
('Fort Cavazos (Hood)',         'FTCAVAZOS',     'Army',         'TX', 'USA'),
('Fort Bliss',                  'FTBLISS',       'Army',         'TX', 'USA'),
('Fort Wainwright',             'FTWAINWRIGHT',  'Army',         'AK', 'USA'),
('Fort Gregg-Adams (Lee)',      'FTGREGGADAMS',  'Army',         'VA', 'USA'),
('Fort Meade',                  'FTMEADE',       'Army',         'MD', 'USA'),
('Fort Belvoir',                'FTBELVOIR',     'Army',         'VA', 'USA'),
('Fort Drum',                   'FTDRUM',        'Army',         'NY', 'USA'),
('Fort Stewart',                'FTSTEWART',     'Army',         'GA', 'USA'),
('Fort Moore (Benning)',        'FTMOORE',       'Army',         'GA', 'USA'),
('Fort Eisenhower (Gordon)',    'FTEISENHOWER',  'Army',         'GA', 'USA'),
('Fort Johnson (Polk)',         'FTJOHNSON',     'Army',         'LA', 'USA'),
('Fort Irwin',                  'FTIRWIN',       'Army',         'CA', 'USA'),
('Schofield Barracks',         'SCHOFIELD',     'Army',         'HI', 'USA'),
-- Navy / Marine Corps
('Naval Air Station Jacksonville','NAS JACKSONVILLE','Navy',     'FL', 'USA'),
('Naval Air Station Key West',  'NAS KEY WEST',  'Navy',         'FL', 'USA'),
('Naval Air Station Pensacola', 'NAS PENSACOLA', 'Navy',         'FL', 'USA'),
('Naval Station Norfolk',       'NS NORFOLK',    'Navy',         'VA', 'USA'),
('Naval Air Station Oceana',    'NAS OCEANA',    'Navy',         'VA', 'USA'),
('Marine Corps Base Quantico',  'MCB QUANTICO',  'Marines',      'VA', 'USA'),
('Marine Corps Base Camp Lejeune','MCB LEJEUNE', 'Marines',      'NC', 'USA'),
('Marine Corps Air Station Cherry Point','MCAS CHERRYPOINT','Marines','NC','USA'),
('Marine Corps Base Camp Pendleton','MCB PENDLETON','Marines',   'CA', 'USA'),
('Marine Corps Air Station Miramar','MCAS MIRAMAR','Marines',    'CA', 'USA'),
('Naval Base San Diego',        'NBSD',          'Navy',         'CA', 'USA'),
('Naval Air Station Lemoore',   'NAS LEMOORE',   'Navy',         'CA', 'USA'),
('Naval Base Kitsap',           'NBK',           'Navy',         'WA', 'USA'),
('Naval Station Rota',          'NS ROTA',       'Navy',         'Andalusia', 'Spain')
ON CONFLICT DO NOTHING;
